[project]
name = "search-gift"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai-tools>=0.14.0",
    "crewai>=0.83.0",
    "pandas>=2.2.3",
    "streamlit>=1.40.2",
    "tiktoken>=0.8.0",
]
